import './globals.css';

import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import { PageFooter } from '@/components/footer';

const inter = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Nextjs TailwindCSS Starter',
    description: 'Generated by Marco Alvarado',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                <PageFooter />
            </body>
        </html>
    );
}
